### ISSUE TITLE
Could not install plugin

### ISSUE THREAD

**Issue by TestAndunR** [DevExpress/generator-testcafe-browser-provider#4]
Error log is attached to the issue

[2018-06-21T08_43_21_592Z-debug.log](https://github.com/DevExpress/generator-testcafe-browser-provider/files/2122796/2018-06-21T08_43_21_592Z-debug.log)

**Comment by AndreyBelym** [comment]
Hi @TestAndunR, I can't reproduce the issue. I guess it's a NPM issue, judging by this line in the log:
```
silly fetchPackageMetaData error for typescript@2.8.3 Unexpected end of JSON input while parsing near '...":"^1.11.2","browseri'
```

I suggest you to  clean npm cache with `npm cache clean -f`, and try to reinstall the generator. If the problem won't gone, contact NPM developers at https://github.com/npm/npm/issues.

**Comment by TestAndunR** [comment]
Hi @AndreyBelym ,
Thanks. It got installed after i cleaned the npm cache👍
